### ISSUE TITLE
Send a mouse click relative to the current mouse position

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#139]
```
mouse.click_relative_self(0,0,1)

When I add this to a script I expect for a mouse click when I press the hotkey 
combination, which is described in the API 
http://autokey.googlecode.com/svn/trunk/doc/scripting/lib.scripting.Mouse-class.
html . Instead I get the error 
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/service.py", line 404, in execute
    exec script.code in self.scope
  File "<string>", line 2, in <module>
AttributeError: Mouse instance has no attribute 'click_relative_self'

I am using version 0.71 of autokey on Linux Mint 10 - 32bit with Gnome.

```

Original issue reported on code.google.com by `mindos...@gmail.com` on 13 Sep 2011 at 10:49

**Comment by GoogleCodeExporter** [comment]
```
This method is only implemented in 0.80 which has not been released yet.
```

Original comment by `cdekter` on 13 Sep 2011 at 9:11
- Changed state: **Invalid**
