### ISSUE TITLE
Required gtk+ version is 2.24, the one included in Ubuntu Lucid is 2.20.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#142]
```
What steps will reproduce the problem?
1. Start the new Autokey 0.80.0
2. Try to create a new phrase
3. See debugging output

What is the expected output? What do you see instead?
Nothing happens.

What version of the product are you using? On what operating system?
Autokey 0.80.0, in Ubuntu Lucid Lynx

Please provide any additional information below.

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 844, in on_new_phrase
    name = self.__getNewItemName("Phrase")
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 827, in __getNewItemName
    dlg = RenameDialog(self.ui, "New %s" % itemType, True, _("Create New %s") % itemType)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 66, in __init__
    builder = get_ui("renamedialog.xml")
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 47, in get_ui
    builder.add_from_file(uiFile)
glib.GError: 
/usr/lib/python2.6/dist-packages/autokey/gtkui/data/renamedialog.xml: required 
gtk+ version 2.24, current version is 2.20
```

Original issue reported on code.google.com by `mar...@pingdom.com` on 29 Sep 2011 at 9:04

**Comment by GoogleCodeExporter** [comment]
```
Current workaround:
Edit /usr/lib/python2.6/dist-packages/autokey/gtkui/data/renamedialog.xml and 
change 2.24 to 2.20 (may break functionality) 
```

Original comment by `mar...@pingdom.com` on 29 Sep 2011 at 1:17

**Comment by GoogleCodeExporter** [comment]
```
Issue 145 has been merged into this issue.
```

Original comment by `cdekter` on 29 Sep 2011 at 9:14

**Comment by GoogleCodeExporter** [comment]
Original comment by `cdekter` on 29 Sep 2011 at 9:19
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r360
```

Original comment by `cdekter` on 29 Sep 2011 at 9:34
- Changed state: **Fixed**
