### ISSUE TITLE
Cannot Create New Phrase After 0.80.0 Upgrade

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#145]
```
What steps will reproduce the problem?
1. Show Main Window in Autokey 0.80.0 
2. Ctrl-N to create new phrase

What is the expected output? What do you see instead?
I expected the pop-up window to appear. Nothing happens... no pop-up, no 
nothing. Thus I cannot create a new phrase.

What version of the product are you using? On what operating system?
Autokey 0.80.0 in Ubuntu 10.04.1 LTS. The previous ver of Autokey worked fine. 
Very handy app, by the way. I was really growing to like it! I hope the fix 
will be easy and quick. It looks like an unsatisfied dependency to me.

Please provide any additional information below.
It looks like 0.80.0 requires a newer ver of GTK+ than I have installed. I 
don't know if LTS will update GTK+ or not. Here's relevant output from 
.xsession-errors:

Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 844, in on_new_phrase
    name = self.__getNewItemName("Phrase")
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 827, in __getNewItemName
    dlg = RenameDialog(self.ui, "New %s" % itemType, True, _("Create New %s") % itemType)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 66, in __init__
    builder = get_ui("renamedialog.xml")
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 47, in get_ui
    builder.add_from_file(uiFile)
glib.GError: 
/usr/lib/python2.6/dist-packages/autokey/gtkui/data/renamedialog.xml: required 
gtk+ version 2.24, current version is 2.20

```

Original issue reported on code.google.com by `andy.ros...@gmail.com` on 29 Sep 2011 at 2:15
- Merged into: #142

**Comment by GoogleCodeExporter** [comment]
```
I just noticed that issue 142 already reported this problem. Will try the 
workaround. Tnx.
```

Original comment by `andy.ros...@gmail.com` on 29 Sep 2011 at 2:19

**Comment by GoogleCodeExporter** [comment]
```
I put the workaround in place and Autokey functions normally again. Thanks for 
this quick fix. I use Autokey to make fast, consistent message board responses 
in the online college course I teach, and I soon came to depend on it. I 
appreciate the skill and effort the developers put into this app. Thank you 
very much.
```

Original comment by `andy.ros...@gmail.com` on 29 Sep 2011 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
I put the workaround in place and Autokey functions normally again. Thanks for 
this quick fix. I use Autokey to make fast, consistent message board responses 
in the online college course I teach, and I soon came to depend on it. I 
appreciate the skill and effort the developers put into this app. Thank you 
very much.
```

Original comment by `andy.ros...@gmail.com` on 29 Sep 2011 at 3:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `cdekter` on 29 Sep 2011 at 9:14
- Changed state: **Duplicate**
