### ISSUE TITLE
autokey daemon dies on first connection from autokey-gtk

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#151]
```
What steps will reproduce the problem?
1. start the autokey daemon as root
2. invoke autokey-gtk as the logged-in user


What is the expected output? What do you see instead?
I expect autokey-gtk to start. Instead, autogtk -l gives:

anthony@vlotus:~$ autokey-gtk -l
INFO - root - Initialising application
INFO - config-manager - Loading config from existing file: 
/home/anthony/.config/autokey/autokey.bin
INFO - root - Initialise global hotkeys
INFO - config-manager - Successfully loaded configuration file
DEBUG - config-manager - Global settings: {'showTrayIcon': True, 
'windowDefaultSize': (600, 400), 'undoUsingBackspace': True, 
'enableQT4Workaround': False, 'promptToSave': True, 'interfaceType': 'XEvDev', 
'showToolbar': True, 'serviceRunning': False, 'isFirstRun': False, 
'sortByUsageCount': True, 'inputSavings': 0, 'hPanePosition': 150, 
'menuTakesFocus': False}
INFO - service - Starting service
Xlib.protocol.request.QueryExtension
DEBUG - interface - Keycodes dict: {'<alt_gr>': 92, '<page_up>': 112, '<f12>': 
96, '<f10>': 76, '<ctrl>': 105, '<f9>': 75, '<alt>': 108, ' ': 65, '<up>': 111, 
'<capslock>': 66, '<pause>': 127, '<home>': 110, '<numlock>': 77, '<f1>': 67, 
'<f7>': 73, '<f5>': 71, '<f3>': 69, '<tab>': 23, '<shift>': 62, '<left>': 113, 
'<backspace>': 22, '<scroll_lock>': 78, '<escape>': 9, '<down>': 116, '<f8>': 
74, '<delete>': 119, '<f11>': 95, '<super>': 134, '<print_screen>': 107, 
'<end>': 115, '<right>': 114, '<menu>': 135, '<f2>': 68, '<insert>': 118, 
'<page_down>': 117, '<f6>': 72, '<enter>': 36, '<f4>': 70}
DEBUG - interface - Alt-Grid: XK_Alt_R, 65514
DEBUG - interface - [(92, 0), (92, 2)]
DEBUG - interface - X Server Keymap
DEBUG - interface - [\] : [(51, 0), (51, 2)]
DEBUG - interface - [|] : [(51, 1), (51, 3), (94, 4)]
DEBUG - interface - [`] : [(49, 0), (49, 2)]
DEBUG - interface - [1] : [(10, 0), (10, 2)]
DEBUG - interface - [2] : [(11, 0), (11, 2)]
DEBUG - interface - [3] : [(12, 0), (12, 2)]
DEBUG - interface - [4] : [(13, 0), (13, 2)]
DEBUG - interface - [5] : [(14, 0), (14, 2)]
DEBUG - interface - [6] : [(15, 0), (15, 2)]
DEBUG - interface - [7] : [(16, 0), (16, 2)]
DEBUG - interface - [8] : [(17, 0), (17, 2)]
DEBUG - interface - [9] : [(18, 0), (18, 2)]
DEBUG - interface - [0] : [(19, 0), (19, 2)]
DEBUG - interface - [-] : [(20, 0), (20, 2)]
DEBUG - interface - [=] : [(21, 0), (21, 2)]
DEBUG - interface - [~] : [(49, 1), (49, 3)]
DEBUG - interface - [!] : [(10, 1), (10, 3)]
DEBUG - interface - [@] : [(11, 1), (11, 3)]
DEBUG - interface - [#] : [(12, 1), (12, 3)]
DEBUG - interface - [$] : [(13, 1), (13, 3)]
DEBUG - interface - [%] : [(14, 1), (14, 3)]
DEBUG - interface - [^] : [(15, 1), (15, 3)]
DEBUG - interface - [&] : [(16, 1), (16, 3)]
DEBUG - interface - [*] : [(17, 1), (17, 3)]
DEBUG - interface - [(] : [(187, 0), (18, 1), (187, 2), (18, 3)]
DEBUG - interface - [)] : [(188, 0), (19, 1), (188, 2), (19, 3)]
DEBUG - interface - [q] : [(24, 0), (24, 2)]
DEBUG - interface - [w] : [(25, 0), (25, 2)]
DEBUG - interface - [e] : [(26, 0), (26, 2)]
DEBUG - interface - [r] : [(27, 0), (27, 2)]
DEBUG - interface - [t] : [(28, 0), (28, 2)]
DEBUG - interface - [y] : [(29, 0), (29, 2)]
DEBUG - interface - [u] : [(30, 0), (30, 2)]
DEBUG - interface - [i] : [(31, 0), (31, 2)]
DEBUG - interface - [o] : [(32, 0), (32, 2)]
DEBUG - interface - [p] : [(33, 0), (33, 2)]
DEBUG - interface - [[] : [(34, 0), (34, 2)]
DEBUG - interface - []] : [(35, 0), (35, 2)]
DEBUG - interface - [a] : [(38, 0), (38, 2)]
DEBUG - interface - [s] : [(39, 0), (39, 2)]
DEBUG - interface - [d] : [(40, 0), (40, 2)]
DEBUG - interface - [f] : [(41, 0), (41, 2)]
DEBUG - interface - [g] : [(42, 0), (42, 2)]
DEBUG - interface - [h] : [(43, 0), (43, 2)]
DEBUG - interface - [j] : [(44, 0), (44, 2)]
DEBUG - interface - [k] : [(45, 0), (45, 2)]
DEBUG - interface - [l] : [(46, 0), (46, 2)]
DEBUG - interface - [;] : [(47, 0), (47, 2)]
DEBUG - interface - ['] : [(48, 0), (48, 2)]
DEBUG - interface - [z] : [(52, 0), (52, 2)]
DEBUG - interface - [x] : [(53, 0), (53, 2)]
DEBUG - interface - [c] : [(54, 0), (54, 2)]
DEBUG - interface - [v] : [(55, 0), (55, 2)]
DEBUG - interface - [b] : [(56, 0), (56, 2)]
DEBUG - interface - [n] : [(57, 0), (57, 2)]
DEBUG - interface - [m] : [(58, 0), (58, 2)]
DEBUG - interface - [,] : [(59, 0), (59, 2)]
DEBUG - interface - [.] : [(60, 0), (60, 2)]
DEBUG - interface - [/] : [(61, 0), (61, 2)]
DEBUG - interface - [Q] : [(24, 1), (24, 3)]
DEBUG - interface - [W] : [(25, 1), (25, 3)]
DEBUG - interface - [E] : [(26, 1), (26, 3)]
DEBUG - interface - [R] : [(27, 1), (27, 3)]
DEBUG - interface - [T] : [(28, 1), (28, 3)]
DEBUG - interface - [Y] : [(29, 1), (29, 3)]
DEBUG - interface - [U] : [(30, 1), (30, 3)]
DEBUG - interface - [I] : [(31, 1), (31, 3)]
DEBUG - interface - [O] : [(32, 1), (32, 3)]
DEBUG - interface - [P] : [(33, 1), (33, 3)]
DEBUG - interface - [{] : [(34, 1), (34, 3)]
DEBUG - interface - [}] : [(35, 1), (35, 3)]
DEBUG - interface - [A] : [(38, 1), (38, 3)]
DEBUG - interface - [S] : [(39, 1), (39, 3)]
DEBUG - interface - [D] : [(40, 1), (40, 3)]
DEBUG - interface - [F] : [(41, 1), (41, 3)]
DEBUG - interface - [G] : [(42, 1), (42, 3)]
DEBUG - interface - [H] : [(43, 1), (43, 3)]
DEBUG - interface - [J] : [(44, 1), (44, 3)]
DEBUG - interface - [K] : [(45, 1), (45, 3)]
DEBUG - interface - [L] : [(46, 1), (46, 3)]
DEBUG - interface - [:] : [(47, 1), (47, 3)]
DEBUG - interface - ["] : [(48, 1), (48, 3)]
DEBUG - interface - [Z] : [(52, 1), (52, 3)]
DEBUG - interface - [X] : [(53, 1), (53, 3)]
DEBUG - interface - [C] : [(54, 1), (54, 3)]
DEBUG - interface - [V] : [(55, 1), (55, 3)]
DEBUG - interface - [B] : [(56, 1), (56, 3)]
DEBUG - interface - [N] : [(57, 1), (57, 3)]
DEBUG - interface - [M] : [(58, 1), (58, 3)]
DEBUG - interface - [<] : [(94, 0), (59, 1), (94, 2), (59, 3)]
DEBUG - interface - [>] : [(60, 1), (94, 1), (60, 3), (94, 3)]
DEBUG - interface - [?] : [(61, 1), (61, 3)]
INFO - interface - Attempting to establish connection to EvDev daemon
INFO - interface - EvDev daemon connected
INFO - interface - EvDev interface thread starting
INFO - service - Service now marked as running
ERROR - interface - Connection to EvDev daemon lost
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/interface.py", line 522, in run
    keyCode, button, state = data.split(',')
ValueError: need more than 1 value to unpack
INFO - interface - Attempting to establish connection to EvDev daemon
INFO - root - Entering main()
INFO - interface - Attempting to establish connection to EvDev daemon
INFO - interface - Attempting to establish connection to EvDev daemon
INFO - interface - Attempting to establish connection to EvDev daemon
INFO - interface - Attempting to establish connection to EvDev daemon
INFO - interface - Attempting to establish connection to EvDev daemon
INFO - interface - Attempting to establish connection to EvDev daemon
INFO - interface - Attempting to establish connection to EvDev daemon


the daemon log gives:
root@vlotus:/home/anthony# tail -f /var/log/autokey-daemon.log

AutoKey daemon starting
Created domain socket
Accepted connection
Keyboards: ['/dev/input/by-path/platform-i8042-serio-0-event-kbd']
Mice: ['/dev/input/by-path/pci-0000:00:1d.0-usb-0:2:1.0-event-mouse', 
'/dev/input/by-path/platform-i8042-serio-2-event-mouse', 
'/dev/input/by-path/platform-i8042-serio-1-event-mouse']
Traceback (most recent call last):
  File "/etc/init.d/autokey", line 131, in <module>
    daemon.start()
  File "/usr/lib/python2.6/dist-packages/autokey/daemon.py", line 94, in start
    self.run()
  File "/etc/init.d/autokey", line 66, in run
    devices = evdev.DeviceGroup(self.get_device_paths())
  File "/usr/lib/python2.6/dist-packages/autokey/evdev.py", line 146, in __init__
    self.devices.append(Device(fileName))
  File "/usr/lib/python2.6/dist-packages/autokey/evdev.py", line 98, in __init__
    self.readMetadata()        
  File "/usr/lib/python2.6/dist-packages/autokey/evdev.py", line 122, in readMetadata
    values = struct.unpack("iiiii", ioctl(self.fd, EVIOCGABS_512 + number, buffer))
IOError: [Errno 22] Invalid argument






What version of the product are you using? On what operating system?

autokey 0.61.7-2 on:
Ubuntu 10.04.3 LTS


Please provide any additional information below.


```

Original issue reported on code.google.com by `aaltem...@gmail.com` on 10 Oct 2011 at 1:01

**Comment by GoogleCodeExporter** [comment]
```
Please switch your interface type to XRecord.
```

Original comment by `cdekter` on 10 Oct 2011 at 8:08
- Changed state: **WontFix**

**Comment by GoogleCodeExporter** [comment]
```
That worked! Thank you!
```

Original comment by `aaltem...@gmail.com` on 11 Oct 2011 at 4:33
