### ISSUE TITLE
"Autokey" package not provided by PPA at version 0.80.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#155]
```
The autokey package will not successfully upgrade from the 0.61.x version 
supplied in the Ubuntu repository to the current version provided by the PPA 
(0.80.3 as of this writing) apparently due to no autokey package existing at 
0.80.3 in the PPA.

What steps will reproduce the problem?
--------------------------------------
1. Install autokey 0.61.7-2 from the Ubuntu Lucid package repository
2. Using 'apt-add-repository' add the ppa:cdekter/ppa; Issue 'sudo apt-get 
update && sudo apt-get install autokey'
3. Attempt to run auto-key gtk

What is the expected output? What do you see instead?
-----------------------------------------------------
The Autokey-gtk GUI, but instead nothing. Only upon further investigation is an 
error message discovered on stdout (see "additional information" below).

Solution:
---------
Remove all autokey packages (possibly followed by 'sudo apt-get autoremove') 
and issue 'sudo apt-get install autokey-gtk'. 


What version of the product are you using? On what operating system?
--------------------------------------------------------------------
Upgrade from 0.67.7 to 0.80.3 on Ubuntu Lucid (10.04).


Please provide any additional information below.
------------------------------------------------

Illustration of the problem using 'apt-show-versions':

kernst@cobalt:/etc/init.d$ apt-show-versions -a -p autokey
Not installed
autokey 0.61.7-2       lucid us.archive.ubuntu.com
autokey 0.71.3-0~lucid lucid ppa.launchpad.net
No stable version
autokey not installed
kernst@cobalt:/etc/init.d$ apt-show-versions -a -p autokey-gtk
autokey-gtk 0.80.3-0~lucid install ok installed
autokey-gtk 0.61.7-2       lucid us.archive.ubuntu.com
autokey-gtk 0.80.3-0~lucid lucid ppa.launchpad.net
No stable version
autokey-gtk/lucid uptodate 0.80.3-0~lucid


An 'autokey' package exists in the PPA at version 0.71.3, and automatically 
pulls in autokey-qt as a dependency. Users of autokey-gtk will get a suprise 
when it no longer works, or produces an error like this:

kernst@cobalt:/etc/init.d$ autokey-gtk
Traceback (most recent call last):
  File "/usr/bin/autokey-gtk", line 20, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 25, in <module>
    import service, monitor
ImportError: No module named monitor

```

Original issue reported on code.google.com by `erns...@gmail.com` on 21 Oct 2011 at 8:53

**Comment by GoogleCodeExporter** [comment]
```
The instructions on the PPA page state how to resolve this problem. Remove 
autokey and autokey-qt and install autokey-gtk.
```

Original comment by `cdekter` on 21 Oct 2011 at 9:00
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
You're right and if I'd read that more closely, I might not have had to take 
the long way round to figure out the problem.

Not trying to be contentious, and not suggesting that you pander to the lowest 
common denominator user (or people like me who can't RTFM), but I still feel 
that either 1) the notice on the PPA should state that 'autokey' should be 
REMOVED prior to upgrade (or else 'apt-get upgrade' will still produce the 
result in this bug report due to the reverse depends), or 2) specify an 
explicit conflict with 'autokey' in the (new) 'autokey-gtk' package.

Thanks for your efforts.
```

Original comment by `erns...@gmail.com` on 21 Oct 2011 at 10:38

**Comment by GoogleCodeExporter** [comment]
```
Upon further reflection, if this bug affects, like, 3 people worldwide (still 
using Ubuntu 10.04), I'd accept it as a WONTFIX. I think the issue still needs 
to be in the bug database, which is why I submitted it.
```

Original comment by `erns...@gmail.com` on 21 Oct 2011 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
That's a fair point... I did ask my Debian maintainer if I should add -replaces 
or -breaks to the 0.80 series but he didn't suggest that. This problem would 
affect anyone who upgraded through Ubuntu 9.10 onwards however.
```

Original comment by `cdekter` on 22 Oct 2011 at 2:50
- Changed state: **OnHold**

**Comment by GoogleCodeExporter** [comment]
Original comment by `cdekter` on 5 Mar 2012 at 8:58
- Changed state: **WontFix**
