### ISSUE TITLE
autokey-gtk fatal error on startup

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#162]
```
reproduce by:
1. build from svn on Ubuntu 10.04 running on MacOS 10.7.2 inside Virtualbox 
4.1.16
2. run autokey-gtk

error Popup appears : AutoKey: Unknown internal child: selection

2011-11-19 09:09:46,909 ERROR - root - Fatal error starting AutoKey: Unknown 
internal child: selection
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 75, in __init__
    self.initialise(options.configure)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 145, in initialise
    self.show_configure()
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 252, in show_configure
    self.configWindow = ConfigWindow(self)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 651, in __init__
    builder = get_ui("mainwindow.xml")
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 50, in get_ui
    builder.add_from_file(uiFile)
GError: Unknown internal child: selection

startup log attached from 'autokey-gtk -l -d >autokey.log'
```

Original issue reported on code.google.com by `haberl...@gmail.com` on 19 Nov 2011 at 8:30

Attachments:
- [autokey.log](https://storage.googleapis.com/google-code-attachments/autokey/issue-162/comment-0/autokey.log)

**Comment by GoogleCodeExporter** [comment]
```
Which revision did you check out?
```

Original comment by `cdekter` on 19 Nov 2011 at 11:58

**Comment by GoogleCodeExporter** [comment]
```
svn info
Path: .
URL: http://autokey.googlecode.com/svn/trunk
Repository Root: http://autokey.googlecode.com/svn
Repository UUID: 65b5f37c-86d1-11de-b610-71a7c637a048
Revision: 398
Node Kind: directory
Schedule: normal
Last Changed Author: cdekter@gmail.com
Last Changed Rev: 397
Last Changed Date: 2011-11-18 13:00:29 +0100 (Fri, 18 Nov 2011)

```

Original comment by `haberl...@gmail.com` on 19 Nov 2011 at 3:07

**Comment by GoogleCodeExporter** [comment]
```
Fixed in r403
```

Original comment by `cdekter` on 20 Nov 2011 at 1:20
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
updated to r403, doesnt work for me yet - no more backtrace but popup still 
appears

log and screenshot attached

-m


```

Original comment by `haberl...@gmail.com` on 20 Nov 2011 at 11:02

Attachments:
- [autokey-2.log](https://storage.googleapis.com/google-code-attachments/autokey/issue-162/comment-4/autokey-2.log)
- [Screenshot.png](https://storage.googleapis.com/google-code-attachments/autokey/issue-162/comment-4/Screenshot.png)

**Comment by GoogleCodeExporter** [comment]
```
Rebooting should cure that.
```

Original comment by `cdekter` on 20 Nov 2011 at 11:13

**Comment by GoogleCodeExporter** [comment]
```
rebooting did not help - same thing.

any more debugging/loggin/version info I can give?

-m
```

Original comment by `haberl...@gmail.com` on 20 Nov 2011 at 12:38

**Comment by GoogleCodeExporter** [comment]
```
this is the current backtrace once I click OK on the error popup:

2011-11-20 14:35:10,614 DEBUG - iomediator - Set modifier <capslock> to False
2011-11-20 14:35:10,614 DEBUG - iomediator - Set modifier <numlock> to True
2011-11-20 14:35:10,615 DEBUG - interface - Grabbing hotkey: [u'<super>'] u'k'
2011-11-20 14:35:10,615 DEBUG - interface - Grabbing hotkey: [u'<shift>', 
u'<super>'] u'k'
2011-11-20 14:35:10,616 DEBUG - interface - Grabbing hotkey: [u'<ctrl>'] u'<f7>'
Xlib.protocol.request.QueryExtension
2011-11-20 14:35:10,623 INFO - interface - XRecord interface thread starting
2011-11-20 14:35:10,634 INFO - service - Service now marked as running
2011-11-20 14:35:10,642 DEBUG - phrase-menu - Sorting phrase menu by usage count
2011-11-20 14:35:10,653 INFO - root - Displaying configuration window
2011-11-20 14:35:12,888 DEBUG - service - Received mouse click - resetting 
buffer
2011-11-20 14:35:12,947 ERROR - root - Fatal error starting AutoKey: Unknown 
internal child: selection
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 75, in __init__
    self.initialise(options.configure)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 145, in initialise
    self.show_configure()
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 252, in show_configure
    self.configWindow = ConfigWindow(self)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 726, in __init__
    self.__initStack()
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 1452, in __initStack
    self.folderPage = FolderPage(self)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 341, in __init__
    self.settingsWidget = SettingsWidget(parentWindow)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 111, in __init__
    self.abbrDialog = AbbrSettingsDialog(parentWindow.ui, parentWindow.app.configManager, self.on_abbr_response)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/dialogs.py", line 90, in __init__
    builder = configwindow.get_ui("abbrsettings.xml")
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 50, in get_ui
    builder.add_from_file(uiFile)
GError: Unknown internal child: selection
2011-11-20 14:35:15,369 DEBUG - service - Received mouse click - resetting 
buffer

```

Original comment by `haberl...@gmail.com` on 20 Nov 2011 at 1:36

**Comment by GoogleCodeExporter** [comment]
```
I tried on a real PC with ubuntu 10.04  - same thing

the only thing in common: base install was from the Linuxcnc 10.04 LTS Live CD
```

Original comment by `haberl...@gmail.com` on 20 Nov 2011 at 2:52

**Comment by GoogleCodeExporter** [comment]
```
I would suggest using a diff tool to compare your copy of mainwindow.xml to the 
current ToT. The error is impossible if you have the correct version as the 
entire section that causes this problem has been commented out.
```

Original comment by `cdekter` on 20 Nov 2011 at 8:14

**Comment by GoogleCodeExporter** [comment]
```
It might be we're looking at the wrong file. mainwindow.xml has the same 
checksum in trunk as all my local copies.

mah@ubuntu-10:/tmp$ wget 
http://autokey.googlecode.com/svn/trunk/src/lib/gtkui/data/mainwindow.xml
--2011-11-21 09:05:41--  
http://autokey.googlecode.com/svn/trunk/src/lib/gtkui/data/mainwindow.xml
Resolving autokey.googlecode.com... 74.125.39.82
Connecting to autokey.googlecode.com|74.125.39.82|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4313 (4.2K) [text/plain]
Saving to: `mainwindow.xml'

100%[===========================================================================
==============================================================================>]
 4,313       --.-K/s   in 0.001s  

2011-11-21 09:05:41 (7.58 MB/s) - `mainwindow.xml' saved [4313/4313]

mah@ubuntu-10:/tmp$ cksum mainwindow.xml 
1289242354 4313 mainwindow.xml
mah@ubuntu-10:/tmp$ cksum `locate mainwindow.xml`
1289242354 4313 
/home/mah/src/autokey-read-only/build/lib.linux-i686-2.6/autokey/gtkui/data/main
window.xml
1289242354 4313 
/home/mah/src/autokey-read-only/debian/autokey-gtk/usr/share/pyshared/autokey/gt
kui/data/mainwindow.xml
1289242354 4313 
/home/mah/src/autokey-read-only/debian/tmp/usr/lib/python2.6/site-packages/autok
ey/gtkui/data/mainwindow.xml
1289242354 4313 
/home/mah/src/autokey-read-only/src/lib/gtkui/data/mainwindow.xml
1289242354 4313 
/home/mah/src/autokey-read-only/src/lib/gtkui/data/.svn/text-base/mainwindow.xml
.svn-base
1289242354 4313 
/usr/lib/python2.6/dist-packages/autokey/gtkui/data/mainwindow.xml
1289242354 4313 /usr/share/pyshared/autokey/gtkui/data/mainwindow.xml

```

Original comment by `haberl...@gmail.com` on 21 Nov 2011 at 8:08

**Comment by GoogleCodeExporter** [comment]
```
Just to add me too on RHEL-6 with autokey-0.81.0
```

Original comment by `matej.c...@gmail.com` on 10 Jan 2012 at 1:39
