### ISSUE TITLE
Crash on script error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#198]
```
What steps will reproduce the problem?
1. make a script with an error, say:
asdf
2. run it

What is the expected output? What do you see instead?

Expect: popup saying "Error in script"
See: crash

What version of the product are you using? On what operating system?
Ubuntu 11.10
0.90.3

Please provide any additional information below.

Stack trace:

Exception in thread Phrase-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 464, in execute
    self.app.notify_error(_("The script '%s' encountered an error") % script.description)
  File "/usr/lib/python2.7/dist-packages/autokey/gtkapp.py", line 230, in notify_error
    self.notifier.notify_error(message)
  File "/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py", line 240, in notify_error
    self.show_notify(message, Gtk.STOCK_DIALOG_ERROR)
  File "/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py", line 246, in show_notify
    n = Notify.Notification("AutoKey", message, iconName)
TypeError: GObject.__init__() takes exactly 0 arguments (3 given)



```

Original issue reported on code.google.com by `ciro.san...@gmail.com` on 5 May 2012 at 8:44

**Comment by GoogleCodeExporter** [comment]
```
Any chance you can test this on Ubuntu 12.04?
```

Original comment by `cdekter` on 7 May 2012 at 9:25

**Comment by GoogleCodeExporter** [comment]
```
I upgraded to Ubuntu 12.04 and I am getting the same thing still:

Exception in thread Phrase-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 464, in execute
    self.app.notify_error(_("The script '%s' encountered an error") % script.description)
  File "/usr/lib/python2.7/dist-packages/autokey/gtkapp.py", line 230, in notify_error
    self.notifier.notify_error(message)
  File "/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py", line 240, in notify_error
    self.show_notify(message, Gtk.STOCK_DIALOG_ERROR)
  File "/usr/lib/python2.7/dist-packages/autokey/gtkui/notifier.py", line 246, in show_notify
    n = Notify.Notification("AutoKey", message, iconName)
TypeError: GObject.__init__() takes exactly 0 arguments (3 given)

```

Original comment by `ciro.san...@gmail.com` on 9 May 2012 at 7:12

**Comment by GoogleCodeExporter** [comment]
```
I had just upgraded to 12.04 from 11.10, but after removing everything and with 
a clean 12.04 install, the problem was gone.

If no one duplicates this on a clean Ubuntu 12.04 install, this can be closed. 
```

Original comment by `ciro.san...@gmail.com` on 10 May 2012 at 5:14

**Comment by GoogleCodeExporter** [comment]
```
This is due to different behaviours in Gnome 3.2 and 3.4 of PyGI. I will try to 
fix but it's not a priority as it works in the latest GTK versions.
```

Original comment by `cdekter` on 15 May 2012 at 2:27
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Fixed for next release
```

Original comment by `cdekter` on 15 May 2012 at 11:15
- Changed state: **Fixed**
