### ISSUE TITLE
Keyboard or mouse recording not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#204]
```
What steps will reproduce the problem?
1. Start Autokey in the command prompt with autokey-gtk -l
2. In Autokey Main Window menu select File -> New -> Script
3. With the newly created script selected go to the Main Window menu and select 
Tools -> Record keyboard/mouse
4. Nothing happends and in the command prompt the result is the following:
  Traceback (most recent call last):
    File "/usr/lib/python2.7/dist-packages/autokey/gtkui/configwindow.py", line 1228, in on_record_keystrokes
      self.__getCurrentPage().record_keystrokes(widget.get_active())        
    File "/usr/lib/python2.7/dist-packages/autokey/gtkui/configwindow.py", line 511, in record_keystrokes
      dlg = RecordDialog(self.ui, self.on_rec_response)
    File "/usr/lib/python2.7/dist-packages/autokey/gtkui/dialogs.py", line 603, in __init__
      self.ui.set_transient_for(parent)
    File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
      return info.invoke(*args, **kwargs)
  TypeError: Expected Gtk.Window, but got GObjectMeta

What is the expected output? What do you see instead?
The expected output is a window to start recording the keyboard or mouse 
actions, but instead nothing happens.

What version of the product are you using? On what operating system?
Autokey 0.90.4 in Ubuntu 12.04

Previously I used Autokey 0.71.4 and the keyboard recording did work.
```

Original issue reported on code.google.com by `raulcorr...@gmail.com` on 23 May 2012 at 9:06

**Comment by GoogleCodeExporter** [comment]
```
See link below for fix:

http://code.google.com/p/autokey/issues/detail?id=221
```

Original comment by `pmoot...@gmail.com` on 28 Dec 2012 at 5:49
