### ISSUE TITLE
Python error on arch linux, python2.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#221]
```
What steps will reproduce the problem?
1. Open autokey-gtk
2. Open tools menu
3. Record KB/Mouse

heres the exception.

---

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/autokey/gtkui/configwindow.py", line 1228, in on_record_keystrokes
    self.__getCurrentPage().record_keystrokes(widget.get_active())        
  File "/usr/lib/python2.7/site-packages/autokey/gtkui/configwindow.py", line 511, in record_keystrokes
    dlg = RecordDialog(self.ui, self.on_rec_response)
  File "/usr/lib/python2.7/site-packages/autokey/gtkui/dialogs.py", line 603, in __init__
    self.ui.set_transient_for(parent)
  File "/usr/lib/python2.7/site-packages/gi/types.py", line 47, in function
    return info.invoke(*args, **kwargs)
TypeError: argument parent: Expected Gtk.Window, but got 
gi.repository.Gtk.Alignment

```

Original issue reported on code.google.com by `ideasma...@gmail.com` on 21 Oct 2012 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
Tested with 0.90.4
```

Original comment by `ideasma...@gmail.com` on 21 Oct 2012 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
I had this same issue. To resolve it I edited:

/usr/lib64/python2.7/site-packages/autokey/gtkui/dialogs.py

and commented out line 603.

#self.ui.set_transient_for(parent)

I have attached the updated file.

```

Original comment by `pmoot...@gmail.com` on 26 Dec 2012 at 10:23

Attachments:
- [dialogs.py](https://storage.googleapis.com/google-code-attachments/autokey/issue-221/comment-2/dialogs.py)

**Comment by GoogleCodeExporter** [comment]
```
Tried the solution on Ubuntu but when I then try to record keyboard keys I get 
the following error:

Gtk:ERROR:/build/buildd/gtk+3.0-3.4.2/./gtk/gtktextview.c:3726:gtk_text_view_val
idate_onscreen: assertion failed: (priv->onscreen_validated)
Aborted (core dumped)

```

Original comment by `raulcorr...@gmail.com` on 4 Jan 2013 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Getting the same error, any fix?
```

Original comment by `robin0...@gmail.com` on 12 Jan 2015 at 7:26

**Comment by GoogleCodeExporter** [comment]
```
I am getting same error and found this with google.

I am leaving a note for other googlers on what was probably other peoples 
solutions and my solution.

I installed and use autokey-qt

# apt-get install autokey-qt

works perfectly.


```

Original comment by `crackil...@gmail.com` on 3 Mar 2015 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
thanks  qt version  worked for me 
```

Original comment by `mikeinje...@gmail.com` on 15 May 2015 at 11:51
