### ISSUE TITLE
Fresh install *-qt - abbreviations not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#241]
```
What steps will reproduce the problem?
1. Run software-managere (terminal > mintinstall)
1. Install autokey-common
2. Install autokey-qt
3. Run autokey (KDE)
4. Insert na new phrase: "m1", content to: "asdfasdf"
5. Set abbreviation to "m1", several options tested, removing of abbreviation 
trigger set.

What is the expected output? What do you see instead?
After typing [m1<enter>] i expect to get [asdfasdf]. Instead output is mod 
modified ([m1<enter>]).


What version of the product are you using? On what operating system?

0.90.1 using KDE Development Platform 4.9.5
Linux Mint 14 
Python 2.7.3


Please provide any additional information below.
Log shows:
Ignored locking error in handle_keypress
Send via event interface
Send special key: ['<backspace>']
Send special key: ['<backspace>']
Sending string: u'asdfasdf'
Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 116, in __eventLoop
    method(*args)
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 578, in __sendString
    self.__checkWorkaroundNeeded()
  File "/usr/lib/python2.7/dist-packages/autokey/interface.py", line 863, in __checkWorkaroundNeeded
    w = self.app.configManager.workAroundApps
AttributeError: ConfigManager instance has no attribute 'workAroundApps'
Reporting IN_MODIFY event at /home/mizy/.config/autokey/autokey.log

```

Original issue reported on code.google.com by `grzegorz...@gmail.com` on 8 Apr 2013 at 10:53

**Comment by GoogleCodeExporter** [comment]
```
I can confirm this also for autokey-gtk 0.90.4, Python 2.7.4, Arch Linux x86_64.

Further, hitting ctrl+f7 (default 'my phrases' hotkey) and selecting the phrase 
does not type it in either -- same error.
```

Original comment by `fintic...@gmail.com` on 20 Apr 2013 at 12:46

**Comment by GoogleCodeExporter** [comment]
```
This is happening for me as well. autokey-qt-0.90.4-2.fc18.noarch Python 2.7.3 
Fedora release 18 (Spherical Cow)


```

Original comment by `c.hendri...@gmail.com` on 22 Apr 2013 at 1:08
