### ISSUE TITLE
AutoKey crashes when inserting certain special characters with the clipboard

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#243]
```
What steps will reproduce the problem?
1. Make a replacement phrase like "( ͡° ͜ʖ ͡°)"
2. Paste using Clipboard (Ctrl+V)
3. Attempt to use the phrase

What is the expected output? What do you see instead?
It should replace my abbreviation with the provided text using my clipboard. I 
tried it with my clipboard because other issues here claimed that would help 
with special chars and the keyboard method only sends "( °  °)".

Instead it just deletes my abbreviation and crashes autokey. This stops x from 
receiving text input and I had to kill autokey using my mouse.

What version of the product are you using? On what operating system?
I'm using version 0.90.4 on Arch Linux

Here's the debug output:
DEBUG:iomediator:Send via clipboard
2013-04-20 00:43:56,337 DEBUG - iomediator - Send via clipboard
DEBUG:service:Ignored locking error in handle_keypress
2013-04-20 00:43:56,338 DEBUG - service - Ignored locking error in 
handle_keypress
DEBUG:interface:Send special key: ['<backspace>']
2013-04-20 00:43:56,340 DEBUG - interface - Send special key: ['<backspace>']
DEBUG:interface:Send special key: ['<backspace>']
2013-04-20 00:43:56,342 DEBUG - interface - Send special key: ['<backspace>']
DEBUG:interface:Send special key: ['<backspace>']
2013-04-20 00:43:56,342 DEBUG - interface - Send special key: ['<backspace>']
DEBUG:interface:Send special key: ['<backspace>']
2013-04-20 00:43:56,343 DEBUG - interface - Send special key: ['<backspace>']
DEBUG:interface:Sending string: u'( \u0361\xb0 \u035c\u0296 \u0361\xb0) '
2013-04-20 00:43:56,344 DEBUG - interface - Sending string: u'( \u0361\xb0 
\u035c\u0296 \u0361\xb0) '
ERROR:interface:Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/autokey/interface.py", line 116, in __eventLoop
    method(*args)
  File "/usr/lib/python2.7/site-packages/autokey/interface.py", line 500, in __sendStringClipboard
    self.__fillClipboard(string)
  File "/usr/lib/python2.7/site-packages/autokey/interface.py", line 537, in __fillClipboard
    self.clipBoard.set_text(string.encode("utf-8"))
  File "/usr/lib/python2.7/site-packages/gi/types.py", line 47, in function
    return info.invoke(*args, **kwargs)
TypeError: set_text() takes exactly 3 arguments (2 given)
2013-04-20 00:43:56,346 ERROR - interface - Error in X event loop thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/autokey/interface.py", line 116, in __eventLoop
    method(*args)
  File "/usr/lib/python2.7/site-packages/autokey/interface.py", line 500, in __sendStringClipboard
    self.__fillClipboard(string)
  File "/usr/lib/python2.7/site-packages/autokey/interface.py", line 537, in __fillClipboard
    self.clipBoard.set_text(string.encode("utf-8"))
  File "/usr/lib/python2.7/site-packages/gi/types.py", line 47, in function
    return info.invoke(*args, **kwargs)
TypeError: set_text() takes exactly 3 arguments (2 given)


```

Original issue reported on code.google.com by `Kallmeye...@gmail.com` on 20 Apr 2013 at 4:54

**Comment by GoogleCodeExporter** [comment]
```
This is what happens to me to. But not always. If I try ten times, I would 
guess that two or three of them actually succeeds.


Operating system: Ubuntu 12.04
autokey-gtk 0.90.4-0~precise
```

Original comment by `gurus.kn...@gmail.com` on 20 Apr 2013 at 8:00
