### ISSUE TITLE
Window freezes during configuring

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#251]
```
What steps will reproduce the problem?
1.start autokey
2.klick on 'show main window'
3. try to set up new phrase or edit existing phrase (rename)

What is the expected output? What do you see instead?
being able to set up new phrase
instead the window freezes and I have to kill the app

What version of the product are you using? On what operating system?
0.90.1-1.1 (autokey-common and -qt)
Debian Sid with KDE 4.10-5

Please provide any additional information below.
 autokey &
[1] 6205
devil@siductionbox:~/Downloads/copy/x86_64$ Fontconfig warning: 
"/etc/fonts/conf.d/50-user.conf", line 9: reading configurations from 
~/.fonts.conf is deprecated.
Xlib.protocol.request.QueryExtension
Xlib.protocol.request.QueryExtension
Exception in thread KeypressHandler-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/dist-packages/autokey/iomediator.py", line 202, in run
    target.handle_keypress(rawKey, modifiers, key, windowName, windowClass)
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 179, in handle_keypress
    currentInput, windowInfo, True)
  File "/usr/lib/python2.7/dist-packages/autokey/service.py", line 304, in __checkTextMatches
    if item.check_input(buffer, windowInfo):
  File "/usr/lib/python2.7/dist-packages/autokey/model.py", line 732, in check_input
    abbr = self._should_trigger_abbreviation(buffer)
  File "/usr/lib/python2.7/dist-packages/autokey/model.py", line 131, in _should_trigger_abbreviation
    if self.__checkInput(buffer, abbr):
  File "/usr/lib/python2.7/dist-packages/autokey/model.py", line 144, in __checkInput
    stringBefore, typedAbbr, stringAfter = self._partition_input(buffer, abbr)
  File "/usr/lib/python2.7/dist-packages/autokey/model.py", line 186, in _partition_input
    stringBefore, typedAbbr, stringAfter = matchString.rpartition(abbr)
ValueError: empty separator

```

Original issue reported on code.google.com by `fe.th...@gmail.com` on 31 Jul 2013 at 8:20

**Comment by GoogleCodeExporter** [comment]
```
Just built autokey 0.9.4 and the same thing happens with autokey-qt. 
autokey-gtk works ok so far (on a qt-kde-system)
```

Original comment by `fe.th...@gmail.com` on 31 Jul 2013 at 11:47
