### ISSUE TITLE
Error running autokey-gtk on command line: gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#265]
```
What steps will reproduce the problem?
1. Install the program using setup.py on a Fedora 19 system
2.  autokey-gtk on the command line

What is the expected output? What do you see instead?
I expect the program to launch. Instead, I see:

ERROR:root:Could not find any typelib for AppIndicator3
Traceback (most recent call last):
  File "/bin/autokey-gtk", line 20, in <module>
    from autokey.gtkapp import Application
  File "/usr/lib/python2.7/site-packages/autokey/gtkapp.py", line 31, in <module>
    from gtkui.configwindow import ConfigWindow
  File "/usr/lib/python2.7/site-packages/autokey/gtkui/configwindow.py", line 20, in <module>
    from gi.repository import Gtk, Pango, GtkSource, Gdk, Gio
  File "/usr/lib64/python2.7/site-packages/gi/importer.py", line 68, in load_module
    dynamic_module._load()
  File "/usr/lib64/python2.7/site-packages/gi/module.py", line 289, in _load
    self._introspection_module = get_introspection_module(self._namespace)
  File "/usr/lib64/python2.7/site-packages/gi/module.py", line 268, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib64/python2.7/site-packages/gi/module.py", line 117, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is 
already loaded

What version of the product are you using? On what operating system?
Autokey is version 0.90.4.
Python is version 2.7.5.
OS is Fedora 19.

Please provide any additional information below.
When I try to launch the app from "Accessories" nothing happens either.
```

Original issue reported on code.google.com by `Christop...@gmail.com` on 26 Nov 2013 at 1:01

**Comment by GoogleCodeExporter** [comment]
```
I added 2 packages on my Fedora 20 machine to get this to work.

yum install gtksourceview3 libappindicator-gtk3
```

Original comment by `blh0...@gmail.com` on 18 Jun 2014 at 10:19
