### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#41]
```
What steps will reproduce the problem?
1.run autokey-gtk
2.
3.

What is the expected output? What do you see instead?
Expected output is for autokey to run.  Instead I see:

~$ autokey-gtk -l
INFO - root - Initialising application
INFO - config-manager - Loading config from existing file:
/home/run4life/.config/autokey/autokey.json
ERROR - config-manager - Error while loading configuration. Cannot recover.
/usr/lib/python2.6/dist-packages/autokey/gtkapp.py:247: GtkWarning: Error
parsing gtk-icon-sizes string:
    'panel-menu=24,24
panel=20,20
gtk-button=18,18
gtk-large-toolbar=24,24'
  dlg.run()
ERROR - root - Fatal error starting AutoKey: No JSON object could be decoded
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 79, in
__init__
    self.initialise(options.configure)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 116, in
initialise
    self.configManager = get_config_manager(self)
  File "/usr/lib/python2.6/dist-packages/autokey/configmanager.py", line
113, in get_config_manager
    configData = json.load(pFile)
  File "/usr/lib/python2.6/json/__init__.py", line 267, in load
    parse_constant=parse_constant, **kw)
  File "/usr/lib/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded


What version of the product are you using? On what operating system?
version 0.70.3-1~karmic on ubuntu 9.10 

Please provide any additional information below.
Did execute a search for this same issue, no results were returned.  

```

Original issue reported on code.google.com by `kho...@gmail.com` on 22 Apr 2010 at 5:00

**Comment by GoogleCodeExporter** [comment]
```
The only way I'll be able to debug this if you can attach a copy of 
autokey.json as
it was at the time of the problem
```

Original comment by `cdekter` on 22 Apr 2010 at 7:47

**Comment by GoogleCodeExporter** [comment]
```
I seem to have resolved the issue by deleting the autokey.json file and 
re-running
autokey.  If I run into the issue again I will attach autokey.json
```

Original comment by `kho...@gmail.com` on 22 Apr 2010 at 8:34

**Comment by GoogleCodeExporter** [comment]
```
Closing due to no further info
```

Original comment by `cdekter` on 22 Sep 2010 at 2:39
- Changed state: **WontFix**
