### ISSUE TITLE
Big memory leak

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#43]
```
Using the latest subversion 0.70 I noticed that Autokey's memory footprint
was a massive 1.8gb and I've only got one phrase setup. I noticed it had
gone up from 256mb to this large number after I had had a few attempts at
using my phrase (which incidentally was pressing one letter followed by the
trigger and it would create the word I'd setup) and it wasn't working until
maybe the 4th or 5th attempt.
I don't think this is expected behaviour is it?


```

Original issue reported on code.google.com by `mrdic...@gmail.com` on 5 May 2010 at 5:08

**Comment by GoogleCodeExporter** [comment]
```
When reporting a bug, make sure you fill in as much information as possible - 
the
template should give you an idea of what information is needed. As is I can't do
anything with this report.
```

Original comment by `cdekter` on 5 May 2010 at 9:49

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I have experienced something similar.  I'm running on a fresh install of Lucid, 
and when I have left AutoKey running on the computer unattended for a couple of 
days, I have found it using close to 2 GB of RAM.  I will try to repeat it to 
see if I can get any clues from the logs, etc., and I'll post back here.

```

Original comment by `dv8box-...@yahoo.com` on 18 Jun 2010 at 2:15

**Comment by GoogleCodeExporter** [comment]
```
How do we get log file of autokey so we can show you the information you need 
to debug the error of this memory leak?
```

Original comment by `mrdic...@gmail.com` on 6 Aug 2010 at 11:32

**Comment by GoogleCodeExporter** [comment]
```
See the troubleshooting wiki page
```

Original comment by `cdekter` on 7 Aug 2010 at 12:31

**Comment by GoogleCodeExporter** [comment]
```
Ah, so simple when you know how....running it now and will report back if it 
happens again......its a great program when it works btw!
```

Original comment by `mrdic...@gmail.com` on 7 Aug 2010 at 6:59

**Comment by GoogleCodeExporter** [comment]
```
I'm getting similar, crashes after a while and takes all my cpu, some error's 
from before the last time it happened?

DEBUG - service - Key: u'k', modifiers: ['<super>']
INFO - service - Matched hotkey phrase/script with prompt=False
DEBUG - service - Script runner executing: Script('arr_up')
DEBUG - interface - Send special key: [u'<up>']
ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/service.py", line 398, in execute
    exec script.code in self.scope
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.6/dist-packages/autokey/scripting.py", line 58, in send_key
    self.mediator.send_key(key.decode("utf-8"))
  File "/usr/lib/python2.6/dist-packages/autokey/iomediator.py", line 283, in send_key
    self.interface.send_key(keyName)
  File "/usr/lib/python2.6/dist-packages/autokey/interface.py", line 487, in send_key
    self.__sendKeyCode(self.__lookupKeyCode(keyName))
  File "/usr/lib/python2.6/dist-packages/autokey/interface.py", line 588, in __sendKeyCode
    self.__sendKeyPressEvent(keyCode, modifiers, theWindow)
  File "/usr/lib/python2.6/dist-packages/autokey/interface.py", line 622, in __sendKeyPressEvent
    focus.send_event(keyEvent)
AttributeError: 'int' object has no attribute 'send_event'



```

Original comment by `tpowe...@gmail.com` on 11 Aug 2010 at 10:44

**Comment by GoogleCodeExporter** [comment]
```
Any further reports of this?
```

Original comment by `cdekter` on 22 Sep 2010 at 2:39

**Comment by GoogleCodeExporter** [comment]
Original comment by `cdekter` on 3 Oct 2010 at 2:24
- Changed state: **Invalid**
