### ISSUE TITLE
Autokey from ubuntu-lucid repo fails to start

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#46]
```
What steps will reproduce the problem?
1. sudo apt-get purge autokey (just to be sure)
2. sudo apt-get install autokey
3. autokey

What is the expected output? What do you see instead?

the program fails at execution and a dialog box is displayed:

"Fatal error starting AutoKey.
maximum recursion depth exceeded while calling a Python object"


What version of the product are you using? On what operating system?

Linux tjefferies 2.6.31-21-generic #59-Ubuntu SMP Wed Mar 24 07:28:27 UTC 2010 
x86_64 GNU/Linux

Ubuntu Lucid using wmii window manager.

Package: autokey
New: yes
State: installed
Automatically installed: no
Version: 0.61.7-2
Priority: optional
Section: universe/gnome
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Uncompressed Size: 49.2k
Depends: autokey-gtk, autokey-common



Please provide any additional information below.

Xlib:  extension "RANDR" missing on display ":0.0".
Traceback (most recent call last):
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.AttributeError'> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 796, in emit
    self.handleError(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 725, in handleError
    traceback.print_exception(ei[0], ei[1], ei[2], None, sys.stderr)
  File "/usr/lib/python2.6/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.6/traceback.py", line 57, in print_tb
    if hasattr(sys, 'tracebacklimit'):
AttributeError: 'module' object has no attribute 'tracebacklimit'
Traceback (most recent call last):
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.AttributeError'> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 796, in emit
    self.handleError(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 725, in handleError
    traceback.print_exception(ei[0], ei[1], ei[2], None, sys.stderr)
  File "/usr/lib/python2.6/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.6/traceback.py", line 57, in print_tb
    if hasattr(sys, 'tracebacklimit'):
AttributeError: 'module' object has no attribute 'tracebacklimit'
Exception RuntimeError: 'maximum recursion depth exceeded while calling a 
Python object' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a 
Python object' in <type 'exceptions.RuntimeError'> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 796, in emit
    self.handleError(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 725, in handleError
    traceback.print_exception(ei[0], ei[1], ei[2], None, sys.stderr)
  File "/usr/lib/python2.6/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
RuntimeError: maximum recursion depth exceeded
Exception RuntimeError: 'maximum recursion depth exceeded while calling a 
Python object' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a 
Python object' in <type 'exceptions.RuntimeError'> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 796, in emit
    self.handleError(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 725, in handleError
    traceback.print_exception(ei[0], ei[1], ei[2], None, sys.stderr)
  File "/usr/lib/python2.6/traceback.py", line 124, in print_exception
    _print(file, 'Traceback (most recent call last):')
RuntimeError: maximum recursion depth exceeded
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a 
Python object' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a 
Python object' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.RuntimeError'> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 796, in emit
    self.handleError(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 725, in handleError
    traceback.print_exception(ei[0], ei[1], ei[2], None, sys.stderr)
RuntimeError: maximum recursion depth exceeded
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a 
Python object' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded while calling a 
Python object' in <type 'exceptions.AttributeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.RuntimeError'> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 796, in emit
    self.handleError(record)
  File "/usr/lib/python2.6/logging/__init__.py", line 725, in handleError
    traceback.print_exception(ei[0], ei[1], ei[2], None, sys.stderr)
RuntimeError: maximum recursion depth exceeded
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.RuntimeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.RuntimeError'> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 796, in emit
    self.handleError(record)
RuntimeError: <unprintable RuntimeError object>
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.RuntimeError'> ignored
Exception RuntimeError: 'maximum recursion depth exceeded in __subclasscheck__' 
in <type 'exceptions.RuntimeError'> ignored
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 796, in emit
    self.handleError(record)
RuntimeError: <unprintable RuntimeError object>
Traceback (most recent call last):
  File "/usr/lib/python2.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.6/logging/__init__.py", line 852, in emit
    StreamHandler.emit(self, record)


```

Original issue reported on code.google.com by `tim.jeff...@gmail.com` on 17 Jun 2010 at 11:39

**Comment by GoogleCodeExporter** [comment]
```
There is a misconfiguration in your X environment - see the first line of the 
the error log. Xrandr seems to be disabled. This shouldn't really be a problem 
but it seems to have triggered a bug in xlib and the Python logging framework - 
quite a coincidence. Whatever the case may be, there is little I can do about 
this. Your best bet is to try and figure out why xrandr is disabled.
```

Original comment by `cdekter` on 18 Jun 2010 at 12:45

**Comment by GoogleCodeExporter** [comment]
Original comment by `cdekter` on 3 Jul 2010 at 4:24
- Changed state: **WontFix**
