### ISSUE TITLE
ImportError: cannot import name Qsci - autokey-qt won't start [Resolved]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#76]
```
autokey-qt 
Traceback (most recent call last):
  File "/usr/bin/autokey-qt", line 5, in <module>
    from autokey.qtapp import Application
  File "/usr/lib/python2.6/site-packages/autokey/qtapp.py", line 32, in <module>
    from qtui.configwindow import ConfigWindow
  File "/usr/lib/python2.6/site-packages/autokey/qtui/configwindow.py", line 25, in <module>
    from PyQt4 import Qsci
ImportError: cannot import name Qsci



---------------

Found the solution:

by installing "qscintilla" and "python-qscintilla" autokey-qt and autokey-gtk 
now starts.

p.s. just wanted to put solution the the problem i've found so that in future 
others don't panic :)

```

Original issue reported on code.google.com by `fast.riz...@gmail.com` on 2 Sep 2010 at 1:10

**Comment by GoogleCodeExporter** [comment]
```
In that case it would be better to post it on the user group...
```

Original comment by `cdekter` on 5 Sep 2010 at 11:18
- Changed state: **Invalid**
