### ISSUE TITLE
autokey-gtk 0.71.1 does not start properly after a fresh install on Lucid

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eadevlin/autokey#93]
```
This is the last output if I start autokey-gtk from the terminal:

/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py:580: GtkWarning: 
gtk_menu_attach_to_widget(): menu already attached to GtkImageMenuItem
  create.set_menu(menu)
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/notifier.py", line 133, in on_show_configure
    self.app.show_configure()
  File "/usr/lib/python2.6/dist-packages/autokey/gtkapp.py", line 211, in show_configure
    self.configWindow = ConfigWindow(self)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 594, in __init__
    self.__initStack()
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 1218, in __initStack
    self.blankPage = BlankPage(self)
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 193, in __init__
    builder = get_ui("blankpage.xml")
  File "/usr/lib/python2.6/dist-packages/autokey/gtkui/configwindow.py", line 48, in get_ui
    builder.add_from_file(uiFile)
glib.GError: Failed to open file 
'/usr/lib/python2.6/dist-packages/autokey/gtkui/data/blankpage.xml': No such 
file or directory

```

Original issue reported on code.google.com by `alex.bepple` on 23 Oct 2010 at 7:40
- Merged into: #92

**Comment by GoogleCodeExporter** [comment]
```
This is a duplicate of #92. Sorry I missed it at first glance.
```

Original comment by `alex.bepple` on 23 Oct 2010 at 7:42

**Comment by GoogleCodeExporter** [comment]
Original comment by `cdekter` on 23 Oct 2010 at 11:13
- Changed state: **Duplicate**
